version: '3.8'
services:
    postgres:
      image: postgres:14.1-alpine
      container_name: postgres_picpe
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "picpe"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
      environment:
        PGUSER: postgres
        POSTGRES_DB: picpe
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        TZ: America/Manaus
      ports:
        - "5432:5432"
      volumes:
        - ./docker/postgres/data:/var/lib/postgresql/data

